=== jjonj/Omni/conductor/tracks/archive/feat_tft_helper_20260101/tft_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TFT Set Data",
  "type": "object",
  "properties": {
    "set_name": { "type": "string" },
    "units": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "cost": { "type": "integer" },
          "traits": { "type": "array", "items": { "type": "string" } },
          "is_carry": { "type": "boolean" },
          "locked": { "type": "boolean" },
          "slots": { "type": "integer", "default": 1 },
          "icon": { "type": "string" }
        },
        "required": ["name", "cost", "traits", "is_carry", "locked"]
      }
    },
    "traits": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": { "type": "integer" }
      }
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "icon": { "type": "string" },
          "is_emblem": { "type": "boolean" },
          "trait": { "type": "string" }
        }
      }
    }
  },
  "required": ["set_name", "units", "traits"]
}

=== jjonj/Omni/OmniSync.Web/www/assets/tft/data/set16.json
{
  "set_name": "set16",
  "units": [
    {
      "name": "Anivia",
      "cost": 1,
      "traits": [
        "Freljord",
        "Invoker"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Anivia.png"
    },
    {
      "name": "Blitzcrank",
      "cost": 1,
      "traits": [
        "Zaun",
        "Juggernaut"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Blitzcrank.png"
    },
    {
      "name": "Briar",
      "cost": 1,
      "traits": [
        "Noxus",
        "Slayer",
        "Juggernaut"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Briar.png"
    },
    {
      "name": "Caitlyn",
      "cost": 1,
      "traits": [
        "Piltover",
        "Longshot"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Caitlyn.png"
    },
    {
      "name": "Illaoi",
      "cost": 1,
      "traits": [
        "Bilgewater",
        "Bruiser"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Illaoi.png"
    },
    {
      "name": "Jarvan IV",
      "cost": 1,
      "traits": [
        "Demacia",
        "Defender"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/JarvanIV.png"
    },
    {
      "name": "Jhin",
      "cost": 1,
      "traits": [
        "Ionia",
        "Gunslinger"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Jhin.png"
    },
    {
      "name": "Kog'Maw",
      "cost": 1,
      "traits": [
        "Void",
        "Arcanist",
        "Longshot"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/KogMaw.png"
    },
    {
      "name": "Lulu",
      "cost": 1,
      "traits": [
        "Yordle",
        "Arcanist"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Lulu.png"
    },
    {
      "name": "Qiyana",
      "cost": 1,
      "traits": [
        "Ixtal",
        "Slayer"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Qiyana.png"
    },
    {
      "name": "Rumble",
      "cost": 1,
      "traits": [
        "Yordle",
        "Defender"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Rumble.png"
    },
    {
      "name": "Shen",
      "cost": 1,
      "traits": [
        "Ionia",
        "Bruiser"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Shen.png"
    },
    {
      "name": "Sona",
      "cost": 1,
      "traits": [
        "Demacia",
        "Invoker"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Sona.png"
    },
    {
      "name": "Viego",
      "cost": 1,
      "traits": [
        "Shadow Isles",
        "Quickstriker"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Viego.png"
    },
    {
      "name": "Aphelios",
      "cost": 2,
      "traits": [
        "Targon"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Aphelios.png"
    },
    {
      "name": "Ashe",
      "cost": 2,
      "traits": [
        "Freljord",
        "Quickstriker"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Ashe.png"
    },
    {
      "name": "Cho'Gath",
      "cost": 2,
      "traits": [
        "Void",
        "Juggernaut"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/ChoGath.png"
    },
    {
      "name": "Ekko",
      "cost": 2,
      "traits": [
        "Zaun",
        "Disruptor"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Ekko.png"
    },
    {
      "name": "Graves",
      "cost": 2,
      "traits": [
        "Bilgewater",
        "Gunslinger"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Graves.png"
    },
    {
      "name": "Neeko",
      "cost": 2,
      "traits": [
        "Ixtal",
        "Arcanist",
        "Defender"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Neeko.png"
    },
    {
      "name": "Orianna",
      "cost": 2,
      "traits": [
        "Piltover",
        "Invoker"
      ],
      "is_carry": false,
      "locked": true,
      "icon_url": "assets/tft/set16/champions/Orianna.png"
    },
    {
      "name": "Poppy",
      "cost": 2,
      "traits": [
        "Demacia",
        "Juggernaut",
        "Yordle"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Poppy.png"
    },
    {
      "name": "Rek'Sai",
      "cost": 2,
      "traits": [
        "Void",
        "Vanquisher"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/RekSai.png"
    },
    {
      "name": "Sion",
      "cost": 2,
      "traits": [
        "Noxus",
        "Bruiser"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Sion.png"
    },
    {
      "name": "Teemo",
      "cost": 2,
      "traits": [
        "Yordle",
        "Longshot"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Teemo.png"
    },
    {
      "name": "Tristana",
      "cost": 2,
      "traits": [
        "Yordle",
        "Gunslinger"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Tristana.png"
    },
    {
      "name": "Tryndamere",
      "cost": 2,
      "traits": [
        "Freljord",
        "Slayer"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Tryndamere.png"
    },
    {
      "name": "Twisted Fate",
      "cost": 2,
      "traits": [
        "Bilgewater",
        "Quickstriker"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/TwistedFate.png"
    },
    {
      "name": "Vi",
      "cost": 2,
      "traits": [
        "Zaun",
        "Defender",
        "Piltover"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Vi.png"
    },
    {
      "name": "Xin Zhao",
      "cost": 2,
      "traits": [
        "Demacia",
        "Ionia",
        "Warden"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/XinZhao.png"
    },
    {
      "name": "Yasuo",
      "cost": 2,
      "traits": [
        "Ionia",
        "Slayer"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Yasuo.png"
    },
    {
      "name": "Yorick",
      "cost": 2,
      "traits": [
        "Shadow Isles",
        "Warden"
      ],
      "is_carry": false,
      "locked": true,
      "icon_url": "assets/tft/set16/champions/Yorick.png"
    },
    {
      "name": "Ahri",
      "cost": 3,
      "traits": [
        "Ionia",
        "Arcanist"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Ahri.png"
    },
    {
      "name": "Darius",
      "cost": 3,
      "traits": [
        "Noxus",
        "Defender"
      ],
      "is_carry": false,
      "locked": true,
      "icon_url": "assets/tft/set16/champions/Darius.png"
    },
    {
      "name": "Dr. Mundo",
      "cost": 3,
      "traits": [
        "Zaun",
        "Bruiser"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/DrMundo.png"
    },
    {
      "name": "Draven",
      "cost": 3,
      "traits": [
        "Noxus",
        "Vanquisher"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Draven.png"
    },
    {
      "name": "Gangplank",
      "cost": 3,
      "traits": [
        "Bilgewater",
        "Slayer",
        "Vanquisher"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Gangplank.png"
    },
    {
      "name": "Gwen",
      "cost": 3,
      "traits": [
        "Shadow Isles",
        "Disruptor"
      ],
      "is_carry": true,
      "locked": true,
      "icon_url": "assets/tft/set16/champions/Gwen.png"
    },
    {
      "name": "Jinx",
      "cost": 3,
      "traits": [
        "Zaun",
        "Gunslinger"
      ],
      "is_carry": true,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Jinx.png"
    },
    {
      "name": "Kennen",
      "cost": 3,
      "traits": [
        "Ionia",
        "Defender",
        "Yordle"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Kennen.png"
    },
    {
      "name": "Kobuko & Yuumi",
      "cost": 3,
      "traits": [
        "Bruiser",
        "Invoker",
        "Yordle"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/KobukoAndYuumi.png"
    },
    {
      "name": "LeBlanc",
      "cost": 3,
      "traits": [
        "Noxus",
        "Invoker"
      ],
      "is_carry": false,
      "locked": true,
      "icon_url": "assets/tft/set16/champions/LeBlanc.png"
    },
    {
      "name": "Leona",
      "cost": 3,
      "traits": [
        "Targon"
      ],
      "is_carry": false,
      "locked": false,
      "icon_url": "assets/tft/set16/champions/Leona.png"
    },
    {
      "name": "Loris",
      "cost": 3,
      "traits": [
        "Piltover",
        "Warden"
      ],
      "is_carry": false,
      "locked": false,
